# Generated by Django 5.1.1 on 2024-09-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_technology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='categories/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('dec', models.CharField(max_length=150)),
            ],
        ),
    ]
